In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\glj523\Downloads\SMDB(3)\SMDB_20260223_095331.csv", low_memory=False, na_values=[""])

In [3]:
df

,library_id,robot_sample_id,archive_sample_id,field_sample_id,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,edna_lysate_plate_id,...,field_sample_label_informal,field_sample_biggest_container_stored_at_globe,field_sample_permit_for_dna_analysis,field_sample_environment_secondary,field_sample_wrong_data,field_sample_parent_id,field_sample_age_estimate_unit,geographical_location_names,field_sample_owned_by_aegis,field_sample_storage_id
0,LV7008889952,LV6000185159,LV3006007926,CGG_3_012447,Yucheng Wang,2024-09-26 00:00:00,SS0110,1.0,357.0,eDNALys106#,...,TLS2019M,sediment block,t,NaN,NaN,NaN,ka BP,China,unknown,NaN
1,Lib221206003,LV7000631300,NaN,NaN,Raphael Morard,2022-02-01 00:00:00,SS0004,195.0,240.0,eDNALys026#,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LV7008890460,LV6000656035,NaN,NaN,Kurt Kjær,2024-10-28 00:00:00,SS0118,129.0,548.0,eDNALys114#,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LV7008865459,LV6000653894,SmplNTC,SmplNTC,Kurt Kjær,2024-12-18 00:00:00,SS0133,15.0,66.0,eDNALys129#,...,SmplNTC,SmplNTC,t,SmplNTC,NaN,NaN,ka BP,SmplNTC,unknown,NaN
4,LV7008888962,LV6000202845,LV3006007861,CGG_3_014254,Yucheng Wang,2024-09-26 00:00:00,SS0110,73.0,357.0,eDNALys106#,...,RiceLake12.22DM,sediment block,t,NaN,NaN,NaN,ka BP,China,unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MARIFR2507,core,t,lacustrine,NaN,NaN,ka BP,Aguelmame Ifrah,true,NaN
37673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HUCIVA/16/B-C/4/6b/2024,tube(s),t,NaN,NaN,NaN,ka BP,Slovakia,unknown,NaN
37674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Fyles leaves site,Sample bag,t,NaN,NaN,NaN,ka BP,Canada,unknown,NaN
37675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Haslund Klostervej MOE 01176 / Feature A620 /B...,tube(s),t,NaN,NaN,NaN,ka BP,Denmark,unknown,NaN
37676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HM4,archive tube(s),f,lacustrine,NaN,NaN,ka BP,Germant; Europe,false,NaN

In [6]:
df = pd.read_csv(r"C:\Users\glj523\Downloads\SMDB(3)\SMDB_20260223_095331.tsv", sep="\t", low_memory=False, na_values=[""])

In [7]:
df

,library_id,robot_sample_id,archive_sample_id,field_sample_id,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,edna_lysate_plate_id,...,field_sample_label_informal,field_sample_biggest_container_stored_at_globe,field_sample_permit_for_dna_analysis,field_sample_environment_secondary,field_sample_wrong_data,field_sample_parent_id,field_sample_age_estimate_unit,geographical_location_names,field_sample_owned_by_aegis,field_sample_storage_id
0,LV7008889952,LV6000185159,LV3006007926,CGG_3_012447,Yucheng Wang,2024-09-26 00:00:00,SS0110,1.0,357.0,eDNALys106#,...,TLS2019M,sediment block,t,NaN,NaN,NaN,ka BP,China,unknown,NaN
1,Lib221206003,LV7000631300,NaN,NaN,Raphael Morard,2022-02-01 00:00:00,SS0004,195.0,240.0,eDNALys026#,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LV7008890460,LV6000656035,NaN,NaN,Kurt Kjær,2024-10-28 00:00:00,SS0118,129.0,548.0,eDNALys114#,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LV7008865459,LV6000653894,SmplNTC,SmplNTC,Kurt Kjær,2024-12-18 00:00:00,SS0133,15.0,66.0,eDNALys129#,...,SmplNTC,SmplNTC,t,SmplNTC,NaN,NaN,ka BP,SmplNTC,unknown,NaN
4,LV7008888962,LV6000202845,LV3006007861,CGG_3_014254,Yucheng Wang,2024-09-26 00:00:00,SS0110,73.0,357.0,eDNALys106#,...,RiceLake12.22DM,sediment block,t,NaN,NaN,NaN,ka BP,China,unknown,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MARIFR2507,core,t,lacustrine,NaN,NaN,ka BP,Aguelmame Ifrah,true,NaN
37673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HUCIVA/16/B-C/4/6b/2024,tube(s),t,NaN,NaN,NaN,ka BP,Slovakia,unknown,NaN
37674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Fyles leaves site,Sample bag,t,NaN,NaN,NaN,ka BP,Canada,unknown,NaN
37675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Haslund Klostervej MOE 01176 / Feature A620 /B...,tube(s),t,NaN,NaN,NaN,ka BP,Denmark,unknown,NaN
37676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,HM4,archive tube(s),f,lacustrine,NaN,NaN,ka BP,Germant; Europe,false,NaN

In [18]:
df

,library_id,robot_sample_id,archive_sample_id,field_sample_id,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,edna_lysate_plate_id,...,field_sample_label_informal,field_sample_biggest_container_stored_at_globe,field_sample_permit_for_dna_analysis,field_sample_environment_secondary,field_sample_wrong_data,field_sample_parent_id,field_sample_age_estimate_unit,geographical_location_names,field_sample_owned_by_aegis,field_sample_storage_id
0,LV7008888962,LV6000202845,LV3006007861,CGG_3_014254,Yucheng Wang,2024-09-26 00:00:00,SS0110,73,357,eDNALys106#,...,RiceLake12.22DM,sediment block,t,\N,\N,\N,ka BP,China,unknown,\N
1,LV7008878816,lv6000621313,LV3006008936,Ejstrup2_0-40 Ejs23001,Mikkel Winther Pedersen,2025-05-27 00:00:00,SS0163,1,110,eDNALys150#,...,ejstrup2_0-40,monolith,t,\N,\N,\N,ka BP,Denmark,unknown,\N
2,LV7008865471,LV6000653871,LV3006107520,SK 2024-5,Kurt Kjær,2024-12-18 00:00:00,SS0133,16,66,eDNALys129#,...,SK 2024-5,sediment block,t,\N,\N,\N,ka BP,Norway,unknown,\N
3,LV7008889990,LV6000202847,LV3006007840,CGG_3_014377,Yucheng Wang,2024-09-26 00:00:00,SS0110,85,357,eDNALys106#,...,RiceLake14.20BM,sediment block,t,\N,\N,\N,ka BP,China,unknown,\N

In [80]:

df = pd.read_csv(r"C:\Users\glj523\Downloads\SMDB_20260220_090123.tsv", sep="\t", low_memory=False, )
df.shape

(37677, 138)

In [81]:
df.dtypes.value_counts()

object     108
float64     30
Name: count, dtype: int64

In [38]:
%env PGPASSWORD=5J8DhII0RRsPW1

env: PGPASSWORD=5J8DhII0RRsPW1

In [39]:
from constants import db_connections

In [59]:
df = pd.read_sql("SELECT * from mini_mega_outer", con=db_connections.ENGINE_READ_ONLY)

In [61]:
df.iloc[8539-3:8539+2]

,library_id,robot_sample_id,archive_sample_id,field_sample_id,wet_lab_customer_name,wet_lab_order_date,wet_lab_order_id,wet_lab_no,wet_lab_total_sample_quantity,edna_lysate_plate_id,...,field_sample_label_informal,field_sample_biggest_container_stored_at_globe,field_sample_permit_for_dna_analysis,field_sample_environment_secondary,field_sample_wrong_data,field_sample_parent_id,field_sample_age_estimate_unit,geographical_location_names,field_sample_owned_by_aegis,field_sample_storage_id
8536,LV3003056838,LVG220224064,None,None,Xihan Chen,2022-02-24,SS0003,64.0,184.0,None,...,None,None,None,None,None,None,None,None,None,None
8537,LV3003056744,LVG220224065,None,None,Xihan Chen,2022-02-24,SS0003,65.0,184.0,None,...,None,None,None,None,None,None,None,None,None,None
8538,LV3003056407,LVG220224065,None,None,Xihan Chen,2022-02-24,SS0003,65.0,184.0,None,...,None,None,None,None,None,None,None,None,None,None
8539,LV3003056473,LVG220224086,None,None,Xihan Chen,2022-02-24,SS0003,86.0,184.0,None,...,None,None,None,None,None,None,None,None,None,None
8540,LV3003056780,LVG220224091,None,None,Xihan Chen,2022-02-24,SS0003,91.0,184.0,None,...,None,None,None,None,None,None,None,None,None,None

In [54]:
df.shape

(37677, 138)

In [30]:
print(df.shape)              # rows, columns
print(df.columns[:10])       # see if header makes sense
print(df.isna().all(axis=1).sum())  # completely empty rows

(37677, 138)
Index(['library_id', 'robot_sample_id', 'archive_sample_id', 'field_sample_id',
       'wet_lab_customer_name', 'wet_lab_order_date', 'wet_lab_order_id',
       'wet_lab_no', 'wet_lab_total_sample_quantity', 'edna_lysate_plate_id'],
      dtype='object')
0

In [15]:
res.iloc[25456, :]

library_id                                 NaN
robot_sample_id                            NaN
archive_sample_id                 LV3006105569
field_sample_id                        RN24042
wet_lab_customer_name                      NaN
                                      ...
field_sample_parent_id                     NaN
field_sample_age_estimate_unit           ka BP
geographical_location_names              Chile
field_sample_owned_by_aegis            unknown
field_sample_storage_id                    NaN
Name: 25456, Length: 138, dtype: object