TODO:
- Error messages should be output to the UI and not to console.

In [2]:
'Producio'.lower()

'producio'

In [6]:
import pandas as pd
from utils import queries
a

In [7]:

df = queries.get_column_dtypes('field_sample_internal')

TypeError: get_column_dtypes() takes 0 positional arguments but 1 was given

In [9]:
flow_cell_id = pd.read_html(r'c:\Users\glj523\OneDrive - University of Copenhagen\Database Design\Req Analysis\Julie\laneBarcode.html')[0]

In [17]:
flow_cell_id.iloc[0][0].split("/")

['HTMW2DSX5 ', '  [all projects] ', '  [all samples] ', '  [all barcodes]']

In [2]:
import os
import pandas as pd
from sqlalchemy import create_engine
import numpy as np
import re
from glob import glob
import psycopg2 as psycop
import sys
from datetime import datetime


database_config = {
    'host': 'dandyweb01fl',
    'database': 'aedna_metadata',
    'port': '5432',
    'user': 'upload_user',
    'password': 'Ce65r-l+!D04',
    'schema_name': 'test'
}

database_config2 = {
    'host': database_config['host'],
    'dbname': database_config['database'],
    'port': database_config['port'],
    'user': database_config['user'],
    'password': database_config['password'],
}

engine = create_engine(f"postgresql://{database_config['user']}:{database_config['password']}@{database_config['host']}:{database_config['port']}/{database_config['database']}")

NameError: name '__file__' is not defined

In [3]:
file_path = r'c:\Users\glj523\Downloads\sheets\archive sample\tsvs\eDNA_Archive_sampling_(2023-10-19_EW_AntarcticaPS104).txt'
file_name = os.path.split(file_path)[-1]
database_table_name = 'archive_sample'
date_format = 'yearfirst'
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

# sheet = pd.read_csv(file_path, sep= '\t', encoding='utf_16', parse_dates=['SamplingDate', 'SubmissionDate'], date_parser=date_parser)

In [30]:
l

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry']

In [31]:
l = list(df.head()['Name'])
l.append('Braund, Mr. Owen Harris')
l

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Braund, Mr. Owen Harris']

In [36]:
set().union(set(l))

{'Allen, Mr. William Henry',
 'Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Heikkinen, Miss. Laina'}

In [15]:
l.add('Allen, Mr. William Henry')

In [16]:
l

{'Allen, Mr. William Henry',
 'Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Heikkinen, Miss. Laina'}

In [14]:
{key: None for key in l}

{'Braund, Mr. Owen Harris': None,
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)': None,
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)': None,
 'Allen, Mr. William Henry': None,
 'Heikkinen, Miss. Laina': None}

In [9]:
db_data = pd.read_sql(sql='SELECT * from test.' + database_table_name, con=engine)
# db_data['database_insert_date_utc'] = db_data['database_insert_date_utc'].astype('datetime64[s, Europe/Copenhagen]')
clean_sheet = clean_up(tsv_file_path=file_path, database_table_name=database_table_name)
clean_sheet['database_insert_by'] = database_config['user']
clean_sheet['from_spreadsheet'] = file_name
clean_sheet['database_insert_datetime_utc'] = pd.Timestamp.now(tz='UTC')
clean_sheet['database_insert_datetime_utc'] = clean_sheet['database_insert_datetime_utc'].astype('datetime64[s, Europe/Copenhagen]')
clean_sheet.to_sql(name=database_table_name, schema=database_config['schema_name'], con=engine, if_exists='append', index=False)

45

In [8]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [17]:
df['qPCR Date'].head()

0    11-07-2022
1    11-07-2022
2    11-07-2022
3    11-07-2022
4    11-07-2022
Name: qPCR Date, dtype: object

In [87]:
l = ['9-7-8', '2009-7-8', '9-7-2008']
a = [True, False]

In [92]:
i = 1
for date_ele in l:
    for b in a:
        date = pd.to_datetime(arg=date_ele, dayfirst=b)
        day = date.day
        month = date.month
        year = date.year
        print(f"{i}  pd.to_datetime(arg='{date_ele}', dayfirst={b}) is parsed as: day: {day}, month: {month}, year: {year} " )
        i += 1
    date = pd.to_datetime(arg=date_ele, yearfirst=True)
    day = date.day
    month = date.month
    year = date.year
    print(f"{i}  pd.to_datetime(arg='{date_ele}', yearfirst=True) is parsed as: day: {day}, month: {month}, year: {year} " )
    i += 1

1  pd.to_datetime(arg='9-7-8', dayfirst=True) is parsed as: day: 9, month: 7, year: 2008
2  pd.to_datetime(arg='9-7-8', dayfirst=False) is parsed as: day: 7, month: 9, year: 2008
3  pd.to_datetime(arg='9-7-8', yearfirst=True) is parsed as: day: 8, month: 7, year: 2009
4  pd.to_datetime(arg='2009-7-8', dayfirst=True) is parsed as: day: 7, month: 8, year: 2009
5  pd.to_datetime(arg='2009-7-8', dayfirst=False) is parsed as: day: 8, month: 7, year: 2009
6  pd.to_datetime(arg='2009-7-8', yearfirst=True) is parsed as: day: 8, month: 7, year: 2009
7  pd.to_datetime(arg='9-7-2008', dayfirst=True) is parsed as: day: 9, month: 7, year: 2008
8  pd.to_datetime(arg='9-7-2008', dayfirst=False) is parsed as: day: 7, month: 9, year: 2008
9  pd.to_datetime(arg='9-7-2008', yearfirst=True) is parsed as: day: 7, month: 9, year: 2008

In [96]:
print('1: ' + str(pd.to_datetime('32-17-08', dayfirst=True))) # day month year
print('1: ' + str(pd.to_datetime('32-17-08', dayfirst=True))) # day month year
print('1: ' + str(pd.to_datetime('32-17-08', dayfirst=True))) # day month year
print('1: ' + str(pd.to_datetime('32-17-08', dayfirst=True))) # day month year
print('1: ' + str(pd.to_datetime('32-17-08', dayfirst=True))) # day month year
print('1: ' + str(pd.to_datetime('32-17-08', dayfirst=True))) # day month year

1: 2032-08-17 00:00:00
1: 2032-08-17 00:00:00
1: 2032-08-17 00:00:00
1: 2032-08-17 00:00:00
1: 2032-08-17 00:00:00
1: 2032-08-17 00:00:00

In [ ]:
print('1: ' + str(pd.to_datetime('9-7-8'))) # month day year
print('2: ' + str(pd.to_datetime('2009-7-8'))) # year month day
print('3: ' + str(pd.to_datetime('9-7-2008'))) # month day year
print('4: ' + str(pd.to_datetime('9-7-8', dayfirst=True))) # day month year
print('5: ' + str(pd.to_datetime('9-7-8', yearfirst=True))) # 
print('6: ' + str(pd.to_datetime('2009-7-8', dayfirst=True))) # 
print('7: ' + str(pd.to_datetime('2009-7-8', yearfirst=True))) #
print('8: ' + str(pd.to_datetime('9-7-2008', yearfirst=True))) #
print('9: ' + str(pd.to_datetime('9-7-2008', dayfirst=True))) #

In [59]:
type(pd.DataFrame({'a': [1,3,4,None]}).astype(pd.Int64Dtype())

SyntaxError: incomplete input (2852890571.py, line 1)

In [16]:
connection = psycop.connect(**database_config2)
cursor = connection.cursor()

In [32]:
cursor.execute(f"SELECT * FROM test.archive_sample;")
a = cursor.fetchall()

In [15]:
connection.commit()
cursor.close()
connection.close()

In [5]:
db_data.dtypes

Archive rack position                               object
Archive RACK name\n(eg. ARack0052)                  object
Archive RACK barcode                                object
Archive TUBE barcode                                object
Depth sampled (tape, cm)                            object
Organic content     (High /Low)                     object
Surface exposed? (ie Back wall hit?)\n(Yes / No)    object
Remarks from sampling (optional)                    object
Sampled by 1 (initials)                             object
Sampled by 2 (initials)                             object
Sampled date (yyyy-mm-dd)                           object
No                                                  object
Submitter\n(initials)                               object
Submission date (yyyy-mm-dd)                        object
Core segment ID\n(fx ISL23_019_02A)                 object
Ordered depth (Calibration tape, cm)                object
Notes from submitter (optional)                     object
database_insert_by                                  object
from_spreadsheet                                    object
database_insert_datetime_utc                        object
dtype: object

In [5]:
db_data.columns

Index(['Archive rack position', 'Archive RACK name\n(eg. ARack0052)',
       'Archive RACK barcode', 'Archive TUBE barcode',
       'Depth sampled (tape, cm)', 'Organic content     (High /Low)',
       'Surface exposed? (ie Back wall hit?)\n(Yes / No)',
       'Remarks from sampling (optional)', 'Sampled by 1 (initials)',
       'Sampled by 2 (initials)', 'Sampled date (yyyy-mm-dd)', 'No',
       'Submitter\n(initials)', 'Submission date (yyyy-mm-dd)',
       'Core segment ID\n(fx ISL23_019_02A)',
       'Ordered depth (Calibration tape, cm)',
       'Notes from submitter (optional)', 'database_insert_by',
       'from_spreadsheet', 'database_insert_datetime_utc'],
      dtype='object')

In [56]:
clean_sheet['database_insert_date_utc'].astype('datetime64[ns, CET]')

0    2024-01-12 08:51:07+01:00
1    2024-01-12 08:51:07+01:00
2    2024-01-12 08:51:07+01:00
3    2024-01-12 08:51:07+01:00
4    2024-01-12 08:51:07+01:00
                ...
62   2024-01-12 08:51:07+01:00
63   2024-01-12 08:51:07+01:00
64   2024-01-12 08:51:07+01:00
65   2024-01-12 08:51:07+01:00
66   2024-01-12 08:51:07+01:00
Name: database_insert_date_utc, Length: 65, dtype: datetime64[ns, CET]

In [55]:
db_data['database_insert_date_utc']

0    2024-01-12 08:50:28+01:00
1    2024-01-12 08:50:28+01:00
2    2024-01-12 08:50:28+01:00
3    2024-01-12 08:50:28+01:00
4    2024-01-12 08:50:28+01:00
                ...
60   2024-01-12 08:50:28+01:00
61   2024-01-12 08:50:28+01:00
62   2024-01-12 08:50:28+01:00
63   2024-01-12 08:50:28+01:00
64   2024-01-12 08:50:28+01:00
Name: database_insert_date_utc, Length: 65, dtype: datetime64[s, Europe/Copenhagen]

In [163]:
pd.testing.assert_frame_equal(db_data, sheet_data)

AssertionError: Attributes of DataFrame.iloc[:, 20] (column name="database_insert_date_utc") are different

Attribute "dtype" are different
[left]:  datetime64[ns, UTC]
[right]: datetime64[us, UTC]

In [154]:
sheet_data.dtypes

Robot RACK position                                object
Robot RACK name (e.g. Rack10)                      object
Robot RACK barcode                                 object
Archive TUBE barcode (check)                       object
Robot TUBE barcode                                 object
Sample mass (mg)                                  float64
SubSampling remarks                                object
Lab assistant (initials)                           object
Subsampling date (yyyy-mm-dd)              datetime64[ns]
No                                                  int64
Submitter\n(initials)                              object
Submission Date (yyyy-mm-dd)               datetime64[ns]
Core- or Bulk sample ID (Optional)                 object
Archive rack position                              object
Archive RACK no. (eg. ARack0052)                   object
Archive RACK barcode                               object
Archive TUBE barcode                               object
Remarks\n(eg. personal project ID)                 object
database_insert_by                                 object
from_spreadsheet                                   object
database_insert_date_utc              datetime64[us, UTC]
dtype: object

In [116]:
db_data.columns.equals(sheet_data.columns)

True

In [117]:
(db_data.iloc[0] == sheet_data.iloc[0]).values

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [152]:
count = 0

for i in range(len(sheet_data)):
    if db_data.iloc[i].equals(sheet_data.iloc[i]) == False:
        print(i)
        count = i
        break

pd.DataFrame({'columns': db_data.columns, 'test': (db_data.iloc[count] == sheet_data.iloc[count]).values, 'sheet vals': sheet_data.iloc[count].values, 'db vals': db_data.iloc[count].values, 'sheet types': sheet_data.iloc[count].apply(type).values, 'db types': db_data.iloc[count].apply(type).values})

0

,columns,test,sheet vals,db vals,sheet types,db types
0,Robot RACK position,True,D08,D08,<class 'str'>,<class 'str'>
1,Robot RACK name (e.g. Rack10),True,Rack161,Rack161,<class 'str'>,<class 'str'>
2,Robot RACK barcode,True,LVL900117571,LVL900117571,<class 'str'>,<class 'str'>
3,Archive TUBE barcode (check),True,LV3005887726,LV3005887726,<class 'str'>,<class 'str'>
4,Robot TUBE barcode,True,LV7005227640,LV7005227640,<class 'str'>,<class 'str'>
5,Sample mass (mg),True,151.0,151.0,<class 'numpy.float64'>,<class 'numpy.float64'>
6,SubSampling remarks,False,NaN,NaN,<class 'float'>,<class 'float'>
7,Lab assistant (initials),True,VSS/FM,VSS/FM,<class 'str'>,<class 'str'>
8,Subsampling date (yyyy-mm-dd),True,2023-10-11 00:00:00,2023-10-11 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
9,No,True,46,46,<class 'numpy.int64'>,<class 'numpy.int64'>
10,Submitter\n(initials),True,KHK,KHK,<class 'str'>,<class 'str'>
11,Submission Date (yyyy-mm-dd),True,2023-09-27 00:00:00,2023-09-27 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
12,Core- or Bulk sample ID (Optional),True,CGG_3_016637,CGG_3_016637,<class 'str'>,<class 'str'>
13,Archive rack position,True,B04,B04,<class 'str'>,<class 'str'>
14,Archive RACK no. (eg. ARack0052),True,ARack0442,ARack0442,<class 'str'>,<class 'str'>
15,Archive RACK barcode,True,LVL600038012,LVL600038012,<class 'str'>,<class 'str'>
16,Archive TUBE barcode,True,LV3005887726,LV3005887726,<class 'str'>,<class 'str'>
17,Remarks\n(eg. personal project ID),True,Tjørnin pilot study,Tjørnin pilot study,<class 'str'>,<class 'str'>
18,database_insert_by,True,upload_user,upload_user,<class 'str'>,<class 'str'>
19,from_spreadsheet,True,eDNA_Subsampling_for_robot_pipeline(230927_KHK...,eDNA_Subsampling_for_robot_pipeline(230927_KHK...,<class 'str'>,<class 'str'>
20,database_insert_date_utc,False,2024-01-11 14:36:49.465135+00:00,2024-01-11 14:36:20.132999+00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...

In [126]:
sheet_data.equals(db_data)

True

AssertionError: DataFrame are different

DataFrame shape mismatch
[left]:  (65, 21)
[right]: (65, 18)

In [135]:
print(pd.testing.assert_frame_equal(db_data, sheet_data, check_names=False))

None

In [125]:
row = 61

pd.DataFrame({'columns': db_data.columns, 'test': (db_data.iloc[row] == sheet_data.iloc[row]).values, 'sheet vals': sheet_data.iloc[row].values, 'db vals': db_data.iloc[row].values, 'sheet types': sheet_data.iloc[row].apply(type).values, 'db types': db_data.iloc[row].apply(type).values})

,columns,test,sheet vals,db vals,sheet types,db types
0,Robot RACK position,True,C03,C03,<class 'str'>,<class 'str'>
1,Robot RACK name (e.g. Rack10),True,Rack162,Rack162,<class 'str'>,<class 'str'>
2,Robot RACK barcode,True,LVL900117572,LVL900117572,<class 'str'>,<class 'str'>
3,Archive TUBE barcode (check),False,NaN,NaN,<class 'float'>,<class 'float'>
4,Robot TUBE barcode,True,LV7005368239,LV7005368239,<class 'str'>,<class 'str'>
5,Sample mass (mg),False,NaN,NaN,<class 'numpy.float64'>,<class 'numpy.float64'>
6,SubSampling remarks,True,negative control,negative control,<class 'str'>,<class 'str'>
7,Lab assistant (initials),True,VSS/FM,VSS/FM,<class 'str'>,<class 'str'>
8,Subsampling date (yyyy-mm-dd),True,2023-10-11 00:00:00,2023-10-11 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
9,No,True,63,63,<class 'numpy.int64'>,<class 'numpy.int64'>
10,Submitter\n(initials),True,KHK,KHK,<class 'str'>,<class 'str'>
11,Submission Date (yyyy-mm-dd),True,2023-09-27 00:00:00,2023-09-27 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
12,Core- or Bulk sample ID (Optional),False,NaN,NaN,<class 'float'>,<class 'float'>
13,Archive rack position,False,NaN,NaN,<class 'float'>,<class 'float'>
14,Archive RACK no. (eg. ARack0052),False,NaN,NaN,<class 'float'>,<class 'float'>
15,Archive RACK barcode,False,NaN,NaN,<class 'float'>,<class 'float'>
16,Archive TUBE barcode,False,NaN,NaN,<class 'float'>,<class 'float'>
17,Remarks\n(eg. personal project ID),False,NaN,NaN,<class 'float'>,<class 'float'>

In [96]:
pd.DataFrame({'columns': db_data.columns, 'test': (db_data.iloc[0] == sheet_data.iloc[0]).values, 'sheet vals': sheet_data.iloc[0].values, 'db vals': db_data.iloc[0].values, 'sheet types': sheet_data.iloc[0].apply(type).values, 'db types': db_data.iloc[0].apply(type).values})

,columns,test,sheet vals,db vals,sheet types,db types
0,Robot RACK position,True,A01,A01,<class 'str'>,<class 'str'>
1,Robot RACK name (e.g. Rack10),True,Rack161,Rack161,<class 'str'>,<class 'str'>
2,Robot RACK barcode,True,LVL900117571,LVL900117571,<class 'str'>,<class 'str'>
3,Archive TUBE barcode (check),True,LV3005888412,LV3005888412,<class 'str'>,<class 'str'>
4,Robot TUBE barcode,True,LV7005368197,LV7005368197,<class 'str'>,<class 'str'>
5,Sample mass (mg),True,163.0,163.0,<class 'numpy.float64'>,<class 'numpy.float64'>
6,SubSampling remarks,False,NaN,NaN,<class 'float'>,<class 'float'>
7,Lab assistant (initials),True,VSS/FM,VSS/FM,<class 'str'>,<class 'str'>
8,Subsampling date (yyyy-mm-dd),True,2023-10-11 00:00:00,2023-10-11 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
9,No,True,1,1,<class 'numpy.int64'>,<class 'numpy.int64'>
10,Submitter\n(initials),True,KHK,KHK,<class 'str'>,<class 'str'>
11,Submission Date (yyyy-mm-dd),True,2023-09-27 00:00:00,2023-09-27 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
12,Core- or Bulk sample ID (Optional),True,CGG_3_017392,CGG_3_017392,<class 'str'>,<class 'str'>
13,Archive rack position,True,C05,C05,<class 'str'>,<class 'str'>
14,Archive RACK no. (eg. ARack0052),True,ARack0440,ARack0440,<class 'str'>,<class 'str'>
15,Archive RACK barcode,True,LVL600038039,LVL600038039,<class 'str'>,<class 'str'>
16,Archive TUBE barcode,True,LV3005888412,LV3005888412,<class 'str'>,<class 'str'>
17,Remarks\n(eg. personal project ID),True,Tjørnin pilot study,Tjørnin pilot study,<class 'str'>,<class 'str'>

In [68]:
pd.DataFrame({'columns': db_data.columns, 'test': (db_data.iloc[0] == sheet_data.iloc[0]).values, 'sheet vals': sheet_data.iloc[0].values, 'db vals': db_data.iloc[0].values, 'sheet types': sheet_data.iloc[0].apply(type).values, 'db types': db_data.iloc[0].apply(type).values})

,columns,test,sheet vals,db vals,sheet types,db types
0,Robot RACK position,True,A01,A01,<class 'str'>,<class 'str'>
1,Robot RACK name (e.g. Rack10),True,Rack161,Rack161,<class 'str'>,<class 'str'>
2,Robot RACK barcode,True,LVL900117571,LVL900117571,<class 'str'>,<class 'str'>
3,Archive TUBE barcode (check),True,LV3005888412,LV3005888412,<class 'str'>,<class 'str'>
4,Robot TUBE barcode,True,LV7005368197,LV7005368197,<class 'str'>,<class 'str'>
5,Sample mass (mg),True,163.0,163.0,<class 'numpy.float64'>,<class 'numpy.float64'>
6,SubSampling remarks,False,NaN,None,<class 'float'>,<class 'NoneType'>
7,Lab assistant (initials),True,VSS/FM,VSS/FM,<class 'str'>,<class 'str'>
8,Subsampling date (yyyy-mm-dd),True,2023-10-11 00:00:00,2023-10-11 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
9,No,True,1,1,<class 'numpy.int64'>,<class 'numpy.int64'>
10,Submitter\n(initials),True,KHK,KHK,<class 'str'>,<class 'str'>
11,Submission Date (yyyy-mm-dd),True,2023-09-27 00:00:00,2023-09-27 00:00:00,<class 'pandas._libs.tslibs.timestamps.Timesta...,<class 'pandas._libs.tslibs.timestamps.Timesta...
12,Core- or Bulk sample ID (Optional),True,CGG_3_017392,CGG_3_017392,<class 'str'>,<class 'str'>
13,Archive rack position,True,C05,C05,<class 'str'>,<class 'str'>
14,Archive RACK no. (eg. ARack0052),True,ARack0440,ARack0440,<class 'str'>,<class 'str'>
15,Archive RACK barcode,True,LVL600038039,LVL600038039,<class 'str'>,<class 'str'>
16,Archive TUBE barcode,True,LV3005888412,LV3005888412,<class 'str'>,<class 'str'>
17,Remarks\n(eg. personal project ID),True,Tjørnin pilot study,Tjørnin pilot study,<class 'str'>,<class 'str'>

In [32]:
sheet_data.iloc[0].equals(db_data.iloc[0])

True

In [79]:
pd.to_datetime(sheet_data['Submission Date (yyyy-mm-dd)'], )

0    2023-09-27
1    2023-09-27
2    2023-09-27
3    2023-09-27
4    2023-09-27
        ...
62   2023-09-27
63   2023-09-27
64   2023-09-27
65   2023-09-27
66   2023-09-27
Name: Submission Date (yyyy-mm-dd), Length: 65, dtype: datetime64[ns]

In [99]:
data = {'date_column': ['2022-01-01', '2023-05-15', '2024/12/31']}
df = pd.DataFrame(data)
pd.to_datetime(df['date_column'], format='ISO8601')

ValueError: Time data 12-13-1014 is not ISO8601 format, at position 3. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [95]:
df

    date_column
0    2022-01-01
1    2023-05-15
2    2024/12/31
3  invalid_date

In [58]:
db_data.equals(sheet_data)

False

In [37]:
len(sheet_data[sheet_data['Robot TUBE barcode'].notnull()])

65

,Robot RACK position,Robot RACK name (e.g. Rack10),Robot RACK barcode,Archive TUBE barcode (check),Robot TUBE barcode,Sample mass (mg),SubSampling remarks,Lab assistant (initials),Subsampling date (yyyy-mm-dd),No,Submitter\n(initials),Submission Date (yyyy-mm-dd),Core- or Bulk sample ID (Optional),Archive rack position,Archive RACK no. (eg. ARack0052),Archive RACK barcode,Archive TUBE barcode,Remarks\n(eg. personal project ID)
0,A01,Rack161,LVL900117571,LV3005888412,LV7005368197,163.0,NaN,VSS/FM,2023-10-11,1,KHK,2023-09-27,CGG_3_017392,C05,ARack0440,LVL600038039,LV3005888412,Tjørnin pilot study
1,B01,Rack161,LVL900117571,LV3005887706,LV7005368189,177.0,NaN,VSS/FM,2023-10-11,2,KHK,2023-09-27,CGG_3_017396,D05,ARack0440,LVL600038039,LV3005887706,Tjørnin pilot study
2,C01,Rack161,LVL900117571,LV3005887709,LV7005368173,169.0,NaN,VSS/FM,2023-10-11,3,KHK,2023-09-27,CGG_3_017399,A06,ARack0440,LVL600038039,LV3005887709,Tjørnin pilot study
3,D01,Rack161,LVL900117571,LV3005887715,LV7005368157,175.0,NaN,VSS/FM,2023-10-11,4,KHK,2023-09-27,CGG_3_017402,B06,ARack0440,LVL600038039,LV3005887715,Tjørnin pilot study
4,E01,Rack161,LVL900117571,LV3005888411,LV7005368149,157.0,NaN,VSS/FM,2023-10-11,5,KHK,2023-09-27,CGG_3_017405,C06,ARack0440,LVL600038039,LV3005888411,Tjørnin pilot study
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,C03,Rack162,LVL900117572,NaN,LV7005368239,NaN,negative control,VSS/FM,2023-10-11,63,KHK,2023-09-27,NaN,NaN,NaN,NaN,NaN,NaN
63,D03,Rack162,LVL900117572,LV3005887717,LV7005368231,152.0,NaN,VSS/FM,2023-10-11,64,KHK,2023-09-27,CGG_3_016664,A02,ARack0443,LVL600038011,LV3005887717,Tjørnin pilot study
64,E03,Rack162,LVL900117572,LV3005887710,LV7005368223,167.0,NaN,VSS/FM,2023-10-11,65,KHK,2023-09-27,CGG_3_016666,B02,ARack0443,LVL600038011,LV3005887710,Tjørnin pilot study
65,F03,Rack162,LVL900117572,LV3005887696,LV7005368215,165.0,NaN,VSS/FM,2023-10-11,66,KHK,2023-09-27,CGG_3_016668,C02,ARack0443,LVL600038011,LV3005887696,Tjørnin pilot study
66,A04,Rack162,LVL900117572,LV3005887716,LV7005368208,156.0,NaN,VSS/FM,2023-10-11,67,KHK,2023-09-27,CGG_3_016670,D02,ARack0443,LVL600038011,LV3005887716,Tjørnin pilot study

In [20]:
db_data.iloc[0][:-3]

Robot RACK position                                   A01
Robot RACK name (e.g. Rack10)                     Rack161
Robot RACK barcode                           LVL900117571
Archive TUBE barcode (check)                 LV3005888412
Robot TUBE barcode                           LV7005368197
Sample mass (mg)                                    163.0
SubSampling remarks                                  None
Lab assistant (initials)                           VSS/FM
Subsampling date (yyyy-mm-dd)                  2023-10-11
No                                                      1
Submitter\n(initials)                                 KHK
Submission Date (yyyy-mm-dd)          2023-09-27 00:00:00
Core- or Bulk sample ID (Optional)           CGG_3_017392
Archive rack position                                 C05
Archive RACK no. (eg. ARack0052)                ARack0440
Archive RACK barcode                         LVL600038039
Archive TUBE barcode                         LV3005888412
Remarks\n(eg. personal project ID)    Tjørnin pilot study
Name: 0, dtype: object

In [17]:
sheet_data.iloc[0][:]

Robot RACK position                                   A01
Robot RACK name (e.g. Rack10)                     Rack161
Robot RACK barcode                           LVL900117571
Archive TUBE barcode (check)                 LV3005888412
Robot TUBE barcode                           LV7005368197
Sample mass (mg)                                    163.0
SubSampling remarks                                   NaN
Lab assistant (initials)                           VSS/FM
Subsampling date (yyyy-mm-dd)                  2023-10-11
No                                                      1
Submitter\n(initials)                                 KHK
Submission Date (yyyy-mm-dd)                   2023-09-27
Core- or Bulk sample ID (Optional)           CGG_3_017392
Archive rack position                                 C05
Archive RACK no. (eg. ARack0052)                ARack0440
Archive RACK barcode                         LVL600038039
Archive TUBE barcode                         LV3005888412
Remarks\n(eg. personal project ID)    Tjørnin pilot study
Name: 0, dtype: object

In [45]:
archive_samples = pd.read_sql(sql='SELECT * from super_simple_db.' + 'archive_sample', con=engine)
robot_samples = pd.read_sql(sql='SELECT * from super_simple_db.' + 'robot_sample', con=engine)
edna = pd.read_sql(sql='SELECT * from super_simple_db.' + 'edna_library', con=engine)
adna = pd.read_sql(sql='SELECT * from super_simple_db.' + 'adna_library', con=engine)
cgg_sediment = pd.read_sql(sql='SELECT * from super_simple_db.' + 'cgg_sediment', con=engine)
cgg_animal = pd.read_sql(sql='SELECT * from super_simple_db.' + 'cgg_animal', con=engine)

In [66]:
sheet = r'C:\Users\glj523\Downloads\sheets\cgg\CGG_Database_Animal_Plant_230907_PSO.xlsx'

In [73]:
def simple_test(file_path, sheet_name, table):
    table = pd.read_sql(sql='SELECT * from super_simple_db.' + table, con=engine)
    sheet = pd.read_excel(file_path, engine='openpyxl', sheet_name=sheet_name)
    sheet = sheet.dropna(axis='columns', how='all')
    sheet = sheet.dropna(axis='index', how='all')
    
    assert sheet.shape[1] == table.shape[1] -3
    assert sheet.shape[0] == table.shape[0]

In [74]:
simple_test(file_path=sheet, sheet_name="Animal_Plant", table='cgg_animal_plant')