In [160]:
user = 'magnu'

In [161]:
import os
import pandas as pd
dir_path = fr"C:\Users\{user}\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\lanebarcode"
file_names = os.listdir(dir_path)
lane_barcodes = pd.DataFrame(file_names)

In [162]:
lane_barcodes.rename(columns={0: 'filename'}, inplace=True)

In [163]:
for row in lane_barcodes.iterrows():
    split = row[1]['filename'].split('.')
    if split[1:] != ['lanebarcode', 'html']:
        raise ValueError(f"Unexpected file format: {row[1]['filename']}")
    else :
        lane_barcodes.at[row[0], 'run'] = split[0]

In [164]:
lane_barcodes['date'] = lane_barcodes['run'].apply(lambda x: x.split('_')[0])
lane_barcodes['date'] = lane_barcodes['date'].apply(lambda x: x[2:] if len(x) == 8 else x)
lane_barcodes['machine'] = lane_barcodes['run'].apply(lambda x: x.split('_')[1])
lane_barcodes['run_no'] = lane_barcodes['run'].apply(lambda x: x.split('_')[2])
lane_barcodes['side'] = lane_barcodes['run'].apply(lambda x: x.split('_')[3][0])
lane_barcodes['flowcell'] = lane_barcodes['run'].apply(lambda x: x.split('_')[3][1:])

In [165]:
assert all(lane_barcodes.iloc[:, 2:].astype(str).map(len).nunique() == 1)

In [166]:
def find_valid_elements(path):
        path_split = path.split('_')
        res = []
        for ele in path_split:
            if len(ele)== 5 and not any(x.islower() for x in ele):
                res.append(ele)
        if len(res) > 0:
            return res
        else:
            return None
lane_barcodes['ttags'] = lane_barcodes.run.apply(find_valid_elements)

In [167]:
lane_barcodes['full_flowcell_id'] = lane_barcodes['side'] + lane_barcodes['flowcell']

In [168]:
helpr_path = fr"C:\Users\{user}\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\Copy of list_all_SeqRuns_2024-2025_edit251113JBT.xlsx"
pool_tags = pd.read_excel(helpr_path)

In [169]:
pool_tags['full_flowcell_id'] = pool_tags['InstrumentSide'] + pool_tags['FlowCellID']
# We don't expect XP runs here
mask = pool_tags['RunSheetID'].apply(lambda x: 'xp' in x.lower() if isinstance(x, str) else x)
assert len(pool_tags[mask]) == 0
mask = pool_tags['full_flowcell_id'].duplicated(keep=False)
pool_tags['duplicate_flowcell'] = mask

In [170]:
# get only unique flowcells that are not xp runs
mask1 = ~pool_tags['full_flowcell_id'].duplicated(keep=False)
clean_pool_tags = pool_tags[mask1]
trash_pool_tags = pool_tags[~mask1]
trash_pool_tags.to_excel(fr"C:\Users\{user}\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\trash_pool_tags.xlsx", index=False)

In [171]:
assert len(set(clean_pool_tags['full_flowcell_id'])) == len(clean_pool_tags)

In [172]:
merged = clean_pool_tags.merge(lane_barcodes, on='full_flowcell_id', how='inner', validate='one_to_many')

In [173]:
assert all(merged['side'] == merged['InstrumentSide']) 
assert not any(merged['filename'].duplicated(keep=False))

In [174]:
correct_files = ['240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina.lanebarcode.html',
'240315_A00706_0844_BH37VGDSX7_ZWT6V_reDMPX.lanebarcode.html',
'20250219_A00706_0914_AHVVLWDSXC.lanebarcode.html',
'240806_A00706_0875_AH5FFKDSX7_77P4L.lanebarcode.html',
'240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new.lanebarcode.html']

In [175]:
# Some flowcell IDs occur in multiple lanebarcode filenames. Those are removed here.
mask = merged['full_flowcell_id'].duplicated(keep=False)
mask2 = merged['filename'].isin(correct_files)
merged_no_dups = merged[~mask | mask2]
assert not any(merged_no_dups['full_flowcell_id'].duplicated(keep=False))
assert len(merged[mask]) == (len(merged) - len(merged_no_dups)) + len(correct_files)

In [176]:
extra_files = merged[mask & ~mask2]
extra_files.to_excel(fr"C:\Users\{user}\OneDrive - University of Copenhagen\Project Lanbarcode batch upload\extra_files.xlsx", index=False)

In [177]:
from pathlib import Path
import sys
import os

def find_project_root():
    path = Path(os.getcwd()).resolve()
    while path != path.root:
        if (path / 'very_rootsy_file.txt').exists():
            return path
        path = path.parent
    return None  # Project root not found

project_root = find_project_root()

sys.path.append(str(project_root))

In [178]:
%env PGPASSWORD=5J8DhII0RRsPW1

env: PGPASSWORD=5J8DhII0RRsPW1

In [179]:
from constants.db_connections import ENGINE, ENGINE_READ_ONLY, SQL_ALCH_CONFIG, PSY_CONN
q = 'select * from flowcell'
flowcell_db = pd.read_sql(q, ENGINE_READ_ONLY)
flowcell_db['full_flowcell_id'] = flowcell_db['flowcell_position'] + flowcell_db['flowcell_id']

q = 'select * from top_unknown_seq_barcodes'
tusb_db = pd.read_sql(q, ENGINE_READ_ONLY)

In [180]:
flowcell_to_upload = merged_no_dups
tusb_to_upload = merged_no_dups

In [181]:
mask = flowcell_to_upload['full_flowcell_id'].isin(flowcell_db['full_flowcell_id'])
flowcell_to_upload = flowcell_to_upload[~mask]

In [182]:
mask = tusb_to_upload['FlowCellID'].isin(tusb_db['flowcell_id'])
tusb_to_upload = tusb_to_upload[~mask]

Get all lanebarcode data to upload into one df

In [183]:
from constants.db_names.names import data
import lane_barcode_parser

fc = []
tpb = []

for file_name in tusb_to_upload.filename:
    file_path = os.path.join(dir_path, file_name)

    tube_tag_col_name = data.flowcell.library_pool_tag()
    read_len_col_name = data.flowcell.read_length()
    seq_machine_col_name = data.flowcell.sequencing_machine()
    seq_date_col_name = data.flowcell.sequencing_date()
    flowcell_pos_col_name = data.flowcell.flowcell_position()
    seq_run_col_name = data.flowcell.sequencing_run()


    # TODO: Make more general:
    sheet = pd.read_html(file_path, thousands=',', decimal='.')

    flowcell_data, top_unknown_barcodes = lane_barcode_parser.parse(df=sheet)

    fc.append(flowcell_data)
    tpb.append(top_unknown_barcodes)

In [184]:
top_unknown_barcodes = pd.concat(tpb, ignore_index=True)
flowcell_data = pd.concat(fc, ignore_index=True)

Get read length, sequencing date, tubetag, seq machine, seq run and flowcell pos merged in

In [185]:
machine_id_map = {
                'A00706': {
                    'name': 'Nova Seq 6000',
                    'rl': '101'
                }
            }
tusb_to_upload.loc[:, 'read_length'] = machine_id_map['A00706']['rl']
tusb_to_upload.loc[:, 'sequencing_machine'] = machine_id_map['A00706']['name']

C:\Users\magnu\AppData\Local\Temp\ipykernel_3396\1588488433.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tusb_to_upload.loc[:, 'read_length'] = machine_id_map['A00706']['rl']
C:\Users\magnu\AppData\Local\Temp\ipykernel_3396\1588488433.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tusb_to_upload.loc[:, 'sequencing_machine'] = machine_id_map['A00706']['name']

In [186]:
tusb_to_upload.loc[:, 'date'] = pd.to_datetime(tusb_to_upload['date'], format='%y%m%d').dt.strftime('%Y-%m-%d')

In [187]:
tusb_to_upload.rename(columns={
    'FlowCellID': data.flowcell.flowcell_id(),
    'run_no': data.flowcell.sequencing_run(),
    'RunDate': data.flowcell.sequencing_date(),
    'InstrumentSide': data.flowcell.flowcell_position(),
    'Tubetag': data.flowcell.library_pool_tag(),
    'filename': 'upload_sheet'
}, inplace=True, errors='raise')

C:\Users\magnu\AppData\Local\Temp\ipykernel_3396\2759310163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tusb_to_upload.rename(columns={

In [188]:
to_upload_final_subset = tusb_to_upload[['upload_sheet', 'sequencing_run', 'sequencing_date', 'sequencing_machine', 'sequencing_run', 'flowcell_position', 'flowcell_id', 'seqc_tube_tag', 'read_length']]

In [189]:
q = 'select column_name_db, column_name_sheet from name_maps.column_names where table_id = 9'
flowcell_name_maps = pd.read_sql(q, ENGINE_READ_ONLY)
flowcell_name_maps = flowcell_name_maps.dropna()
flowcell_name_maps.index = flowcell_name_maps['column_name_sheet']
flowcell_name_maps.drop(columns=['column_name_sheet'], inplace=True)

In [190]:
q = 'select column_name_db, column_name_sheet from name_maps.column_names where table_id = 18'
tusb_name_maps = pd.read_sql(q, ENGINE_READ_ONLY)
tusb_name_maps = tusb_name_maps.dropna()
tusb_name_maps.index = tusb_name_maps['column_name_sheet']
tusb_name_maps.drop(columns=['column_name_sheet'], inplace=True)

In [191]:
translator_tusb = tusb_name_maps.to_dict(orient='dict')['column_name_db']
translator_fc = flowcell_name_maps.to_dict(orient='dict')['column_name_db']

In [192]:
flowcell_data = flowcell_data.rename(columns=translator_fc)

In [193]:
# to_upload_final_fc = flowcell_data.merge(to_upload_final_subset, how='inner', validate='many_to_one')
to_upload_final_tusb = tusb_to_upload.merge(to_upload_final_subset, how='inner', validate='many_to_one', on='flowcell_id')

In [194]:
to_upload_final_subset

,upload_sheet,sequencing_run,sequencing_date,sequencing_machine,sequencing_run,flowcell_position,flowcell_id,seqc_tube_tag,read_length
0,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,0926,2025-04-15,Nova Seq 6000,0926,B,HVVTHDSXC,5OWD7,101
6,20250122_A00706_0912_BHVV2KDSXC.lanebarcode.html,0912,2025-01-22,Nova Seq 6000,0912,B,HVV2KDSXC,YDWCH,101
7,20250115_A00706_0909_BH5FG7DSX7.lanebarcode.html,0909,2025-01-15,Nova Seq 6000,0909,B,H5FG7DSX7,EDS7D,101
8,20250113_A00706_0907_BH5FG2DSX7.lanebarcode.html,0907,2025-01-13,Nova Seq 6000,0907,B,H5FG2DSX7,GCZGV,101
9,20250110_A00706_0904_BH5FC5DSX7.lanebarcode.html,0904,2025-01-10,Nova Seq 6000,0904,B,H5FC5DSX7,ACGTD,101
10,20250106_A00706_0900_BHCJY7DSX7.lanebarcode.html,0900,2025-01-06,Nova Seq 6000,0900,B,HCJY7DSX7,S84I4,101
11,20250103_A00706_0899_BH5CVCDSX7.lanebarcode.html,0899,2025-01-03,Nova Seq 6000,0899,B,H5CVCDSX7,RYLXU,101
12,20241129_A00706_0894_BH5FLYDSX7.lanebarcode.html,0894,2024-11-29,Nova Seq 6000,0894,B,H5FLYDSX7,CGJVB,101
13,20241106_A00706_0892_BH5CTKDSX7.lanebarcode.html,0892,2024-11-06,Nova Seq 6000,0892,B,H5CTKDSX7,3ANXN,101
14,240924_A00706_0882_BH5CW5DSX7_AMT6F.lanebarcod...,0882,2024-09-24,Nova Seq 6000,0882,B,H5CW5DSX7,AMT6F,101
15,240918_A00706_0880_BH5FCMDSX7_ZMXBJ.lanebarcod...,0880,2024-09-18,Nova Seq 6000,0880,B,H5FCMDSX7,ZMXBJ,101
16,240916_A00706_0878_BH5CWLDSX7_BMBMU.lanebarcod...,0878,2024-09-16,Nova Seq 6000,0878,B,H5CWLDSX7,BMBMU,101
17,240806_A00706_0874_BH5CVHDSX7_I7KZE.lanebarcod...,0874,2024-08-06,Nova Seq 6000,0874,B,H5CVHDSX7,I7KZE,101
18,240801_A00706_0872_BH5FG3DSX7_L53HZ.lanebarcod...,0872,2024-08-01,Nova Seq 6000,0872,B,H5FG3DSX7,L53HZ,101
19,240730_A00706_0871_BH5FH5DSX7_N54I2.lanebarcod...,0871,2024-07-30,Nova Seq 6000,0871,B,H5FH5DSX7,N54I2,101
21,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina.lan...,0869,2024-07-24,Nova Seq 6000,0869,B,H5F2GDSX7,PQFUO,101
23,240704_A00706_0864_BH5FCVDSX7_OBXCQ.lanebarcod...,0864,2024-07-04,Nova Seq 6000,0864,B,H5FCVDSX7,OBXCQ,101
35,240219_A00706_0828_BH37V3DSX7_607B.lanebarcode...,0828,2024-02-19,Nova Seq 6000,0828,B,H37V3DSX7,KLN5V,101
39,20250423_A00706_0929_AHVVN7DSXC.lanebarcode.html,0929,2025-04-23,Nova Seq 6000,0929,A,HVVN7DSXC,DGCRS,101
40,20250415_A00706_0927_AHVV3CDSXC.lanebarcode.html,0927,2025-04-15,Nova Seq 6000,0927,A,HVV3CDSXC,KWVET,101
41,20250311_A00706_0925_AHVV52DSXC.lanebarcode.html,0925,2025-03-11,Nova Seq 6000,0925,A,HVV52DSXC,OYJYE,101
45,20250219_A00706_0914_AHVVLWDSXC.lanebarcode.html,0914,2025-02-19,Nova Seq 6000,0914,A,HVVLWDSXC,24M2E,101
47,20250117_A00706_0910_AH5F73DSX7.lanebarcode.html,0910,2025-01-17,Nova Seq 6000,0910,A,H5F73DSX7,2PU65,101
48,20250113_A00706_0906_AH5F7YDSX7.lanebarcode.html,0906,2025-01-13,Nova Seq 6000,0906,A,H5F7YDSX7,ACJXF,101
49,20250115_A00706_0908_AH5FCCDSX7.lanebarcode.html,0908,2025-01-15,Nova Seq 6000,0908,A,H5FCCDSX7,YCFRD,101
50,20250108_A00706_0903_AH5FC3DSX7.lanebarcode.html,0903,2025-01-08,Nova Seq 6000,0903,A,H5FC3DSX7,J88M8,101
51,20250106_A00706_0901_AH5FCWDSX7.lanebarcode.html,0901,2025-01-06,Nova Seq 6000,0901,A,H5FCWDSX7,G8KYJ,101
52,20250103_A00706_0898_AH5FMHDSX7.lanebarcode.html,0898,2025-01-03,Nova Seq 6000,0898,A,H5FMHDSX7,JYCPK,101
53,20241108_A00706_0893_AH5CVTDSX7.lanebarcode.html,0893,2024-11-08,Nova Seq 6000,0893,A,H5CVTDSX7,J3TAV,101
54,240913_A00706_0877_AH5FFCDSX7_77MZJ.lanebarcod...,0877,2024-09-13,Nova Seq 6000,0877,A,H5FFCDSX7,77MZJ,101
57,240801_A00706_0873_AH5CY7DSX7_E5VBT.lanebarcod...,0873,2024-08-01,Nova Seq 6000,0873,A,H5CY7DSX7,E5VBT,101
58,240730_A00706_0870_AH5FG5DSX7_QQESO.lanebarcod...,0870,2024-07-30,Nova Seq 6000,0870,A,H5FG5DSX7,QQESO,101
60,240621_A00706_0860_AH5F3TDSX7_L5WAS.lanebarcod...,0860,2024-06-21,Nova Seq 6000,0860,A,H5F3TDSX7,L5WAS,101
61,240507_A00706_0857_AH5FC2DSX7_BWDQD.lanebarcod...,0857,2024-05-07,Nova Seq 6000,0857,A,H5FC2DSX7,BWDQD,101
69,240219_A00706_0829_AH32TTDSX7_606A.lanebarcode...,0829,2024-02-19,Nova Seq 6000,0829,A,H32TTDSX7,2KESP,101
72,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new...,0826,2024-02-16,Nova Seq 6000,0826,A,H3725DSX7,L8R4I,101
76,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,0811,2024-01-26,Nova Seq 6000,0811,A,HTMW2DSX5,ZTM3M,101

In [195]:
tusb_to_upload

,ID,BSSHRunID,WorkingID,seqc_tube_tag,RunSheetID,sequencing_date,InstrumentID,flowcell_id,flowcell_position,SequencingOK,...,upload_sheet,run,date,machine,sequencing_run,side,flowcell,ttags,read_length,sequencing_machine
0,333,250415_A00706_0926_BHVVTHDSXC,250410_5OWD7_Xihan,5OWD7,250415_S4FCB,2025-04-15,A00706,HVVTHDSXC,B,True,...,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,20250415_A00706_0926_BHVVTHDSXC,2025-04-15,A00706,0926,B,HVVTHDSXC,None,101,Nova Seq 6000
6,305,250122_A00706_0912_BHVV2KDSXC,250102_YDWCH_Suzan,YDWCH,250122_S4FCB,2025-01-22,A00706,HVV2KDSXC,B,True,...,20250122_A00706_0912_BHVV2KDSXC.lanebarcode.html,20250122_A00706_0912_BHVV2KDSXC,2025-01-22,A00706,0912,B,HVV2KDSXC,None,101,Nova Seq 6000
7,296,250115_A00706_0909_BH5FG7DSX7,250102_EDS7D_Suzan,EDS7D,250115_S4FCB,2025-01-15,A00706,H5FG7DSX7,B,True,...,20250115_A00706_0909_BH5FG7DSX7.lanebarcode.html,20250115_A00706_0909_BH5FG7DSX7,2025-01-15,A00706,0909,B,H5FG7DSX7,None,101,Nova Seq 6000
8,294,250113_A00706_0907_BH5FG2DSX7,241223_GCZGV_Suzan,GCZGV,250113_S4FCB,2025-01-13,A00706,H5FG2DSX7,B,True,...,20250113_A00706_0907_BH5FG2DSX7.lanebarcode.html,20250113_A00706_0907_BH5FG2DSX7,2025-01-13,A00706,0907,B,H5FG2DSX7,None,101,Nova Seq 6000
9,292,250110_A00706_0904_BH5FC5DSX7,241223_ACGTD_Suzan,ACGTD,250110_S4FCB,2025-01-10,A00706,H5FC5DSX7,B,True,...,20250110_A00706_0904_BH5FC5DSX7.lanebarcode.html,20250110_A00706_0904_BH5FC5DSX7,2025-01-10,A00706,0904,B,H5FC5DSX7,None,101,Nova Seq 6000
10,287,250106_A00706_0900_BHCJY7DSX7,241220_S84I4_Suzan,S84I4,250106_S4FCB,2025-01-06,A00706,HCJY7DSX7,B,True,...,20250106_A00706_0900_BHCJY7DSX7.lanebarcode.html,20250106_A00706_0900_BHCJY7DSX7,2025-01-06,A00706,0900,B,HCJY7DSX7,None,101,Nova Seq 6000
11,284,250103_A00706_0899_BH5CVCDSX7,241212_RYLXU_Suzan,RYLXU,250103_S4FCB,2025-01-03,A00706,H5CVCDSX7,B,True,...,20250103_A00706_0899_BH5CVCDSX7.lanebarcode.html,20250103_A00706_0899_BH5CVCDSX7,2025-01-03,A00706,0899,B,H5CVCDSX7,None,101,Nova Seq 6000
12,275,241129_A00706_0894_BH5FLYDSX7,241029_CGJVB_Maria,CGJVB,241129_S4FCB,2024-11-29,A00706,H5FLYDSX7,B,True,...,20241129_A00706_0894_BH5FLYDSX7.lanebarcode.html,20241129_A00706_0894_BH5FLYDSX7,2024-11-29,A00706,0894,B,H5FLYDSX7,None,101,Nova Seq 6000
13,268,241106_A00706_0892_BH5CTKDSX7,241023_3ANXN_Maria,3ANXN,241106_S4FCB,2024-11-06,A00706,H5CTKDSX7,B,True,...,20241106_A00706_0892_BH5CTKDSX7.lanebarcode.html,20241106_A00706_0892_BH5CTKDSX7,2024-11-06,A00706,0892,B,H5CTKDSX7,None,101,Nova Seq 6000
14,204,240924_A00706_0882_BH5CW5DSX7,240903_AMT6F_Maria,AMT6F,240924_S4FCB,2024-09-24,A00706,H5CW5DSX7,B,True,...,240924_A00706_0882_BH5CW5DSX7_AMT6F.lanebarcod...,240924_A00706_0882_BH5CW5DSX7_AMT6F,2024-09-24,A00706,0882,B,H5CW5DSX7,[AMT6F],101,Nova Seq 6000
15,206,240918_A00706_0880_BH5FCMDSX7,240903_ZMXBJ_Maria,ZMXBJ,240918_S4FCB,2024-09-18,A00706,H5FCMDSX7,B,True,...,240918_A00706_0880_BH5FCMDSX7_ZMXBJ.lanebarcod...,240918_A00706_0880_BH5FCMDSX7_ZMXBJ,2024-09-18,A00706,0880,B,H5FCMDSX7,[ZMXBJ],101,Nova Seq 6000
16,205,240916_A00706_0878_BH5CWLDSX7,240903_BMBMU_Maria,BMBMU,240916_S4FCB,2024-09-16,A00706,H5CWLDSX7,B,True,...,240916_A00706_0878_BH5CWLDSX7_BMBMU.lanebarcod...,240916_A00706_0878_BH5CWLDSX7_BMBMU,2024-09-16,A00706,0878,B,H5CWLDSX7,[BMBMU],101,Nova Seq 6000
17,191,240806_A00706_0874_BH5CVHDSX7,240724_I7KZE_Maria,I7KZE,240806_S4FCB,2024-08-06,A00706,H5CVHDSX7,B,True,...,240806_A00706_0874_BH5CVHDSX7_I7KZE.lanebarcod...,240806_A00706_0874_BH5CVHDSX7_I7KZE,2024-08-06,A00706,0874,B,H5CVHDSX7,[I7KZE],101,Nova Seq 6000
18,189,240801_A00706_0872_BH5FG3DSX7,240723_L53HZ_Suzan,L53HZ,240801_S4FCB,2024-08-01,A00706,H5FG3DSX7,B,True,...,240801_A00706_0872_BH5FG3DSX7_L53HZ.lanebarcod...,240801_A00706_0872_BH5FG3DSX7_L53HZ,2024-08-01,A00706,0872,B,H5FG3DSX7,[L53HZ],101,Nova Seq 6000
19,187,240730_A00706_0871_BH5FH5DSX7,240723_N54I2_Suzan,N54I2,240730_S4FCB,2024-07-30,A00706,H5FH5DSX7,B,True,...,240730_A00706_0871_BH5FH5DSX7_N54I2.lanebarcod...,240730_A00706_0871_BH5FH5DSX7_N54I2,2024-07-30,A00706,0871,B,H5FH5DSX7,[N54I2],101,Nova Seq 6000
21,185,240724_A00706_0869_BH5F2GDSX7,240709_PQFUO_Rebecca,PQFUO,240724_S4FCB,2024-07-24,A00706,H5F2GDSX7,B,True,...,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina.lan...,240724_A00706_0869_BH5F2GDSX7_PQFUO_Marina,2024-07-24,A00706,0869,B,H5F2GDSX7,[PQFUO],101,Nova Seq 6000
23,179,240704_A00706_0864_BH5FCVDSX7,240628_OBXCQ_Maria,OBXCQ,240704_S4FCB,2024-07-04,A00706,H5FCVDSX7,B,True,...,240704_A00706_0864_BH5FCVDSX7_OBXCQ.lanebarcod...,240704_A00706_0864_BH5FCVDSX7_OBXCQ,2024-07-04,A00706,0864,B,H5FCVDSX7,[OBXCQ],101,Nova Seq 6000
35,10,240219_A00706_0828_BH37V3DSX7,240209_KLN5V_Maria,KLN5V,240219_S4FCB,2024-02-19,A00706,H37V3DSX7,B,True,...,240219_A00706_0828_BH37V3DSX7_607B.lanebarcode...,240219_A00706_0828_BH37V3DSX7_607B,2024-02-19,A00706,0828,B,H37V3DSX7,None,101,Nova Seq 6000
39,338,250423_A00706_0929_AHVVN7DSXC,250402_DGCRS_Vlatka,DGCRS,250423_S4FCA,2025-04-23,A00706,HVVN7DSXC,A,True,...,20250423_A00706_0929_AHVVN7DSXC.lanebarcode.html,20250423_A00706_0929_AHVVN7DSXC,2025-04-23,A00706,0929,A,HVVN7DSXC,None,101,Nova Seq 6000
40,332,250415_A00706_0927_AHVV3CDSXC,250319_KWVET_Mikkel,KWVET,250415_S4FCA,2025-04-15,A00706,HVV3CDSXC,A,True,...,20250415_A00706_0927_AHVV3CDSXC.lanebarcode.html,20250415_A00706_0927_AHVV3CDSXC,2025-04-15,A00706,0927,A,HVV3CDSXC,None,101,Nova Seq 6000
41,331,250311_A00706_0925_AHVV52DSXC,250123_OYJYE_Suzan,OYJYE,250311_S4FCA,2025-03-11,A00706,HVV52DSXC,A,True,...,20250311_A00706_0925_AHVV52DSXC.lanebarcode.html,20250311_A00706_0925_AHVV52DSXC,2025-03-11,A00706,0925,A,HVV52DSXC,None,101,Nova Seq 6000
45,316,250219_A00706_0914_AHVVLWDSXC,250127_24M2E_Caeg,24M2E,250219_S4FCA,2025-02-19,A00706,HVVLWDSXC,A,True,...,20250219_A00706_0914_AHVVLWDSXC.lanebarcode.html,20250219_A00706_0914_AHVVLWDSXC,2025-02-19,A00706,0914,A,HVVLWDSXC,None,101,Nova Seq 6000
47,302,250117_A00706_0910_AH5F73DSX7,250114_2PU65_Ruairidh,2PU65,250117_S4FCA,2025-01-17,A00706,H5F73DSX7,A,True,...,20250117_A00706_0910_AH5F73DSX7.lanebarcode.html,20250117_A00706_0910_AH5F73DSX7,2025-01-17,A00706,0910,A,H5F73DSX7,None,101,Nova Seq 6000
48,293,250113_A00706_0906_AH5F7YDSX7,241223_ACJXF_Suzan,ACJXF,250113_S4FCA,2025-01-13,A00706,H5F7YDSX7,A,True,...,20250113_A00706_0906_AH5F7YDSX7.lanebarcode.html,20250113_A00706_0906_AH5F7YDSX7,2025-01-13,A00706,0906,A,H5F7YDSX7,None,101,Nova Seq 6000
49,295,250115_A00706_0908_AH5FCCDSX7,241223_YCFRD_Suzan,YCFRD,250110_S4FCA,2025-01-15,A00706,H5FCCDSX7,A,True,...,20250115_A00706_0908_AH5FCCDSX7.lanebarcode.html,20250115_A00706_0908_AH5FCCDSX7,2025-01-15,A00706,0908,A,H5FCCDSX7,None,101,Nova Seq 6000
50,289,250108_A00706_0903_AH5FC3DSX7,241220_J88M8_Suzan,J88M8,250108_S4FCA,2025-01-08,A00706,H5FC3DSX7,A,True,...,20250108_A00706_0903_AH5FC3DSX7.lanebarcode.html,20250108_A00706_0903_AH5FC3DSX7,2025-01-08,A00706,0903,A,H5FC3DSX7,None,101,Nova Seq 6000
51,285,250106_A00706_0901_AH5FCWDSX7,241220_G8KYJ_Suzan,G8KYJ,250106_S4FCA,2025-01-06,A00706,H5FCWDSX7,A,True,...,20250106_A00706_0901_AH5FCWDSX7.lanebarcode.html,20250106_A00706_0901_AH5FCWDSX7,2025-01-06,A00706,0901,A,H5FCWDSX7,None,101,Nova Seq 6000
52,283,250103_A00706_0898_AH5FMHDSX7,241212_JYCPK_Suzan,JYCPK,250103_S4FCA,2025-01-03,A00706,H5FMHDSX7,A,True,...,20250103_A00706_0898_AH5FMHDSX7.lanebarcode.html,20250103_A00706_0898_AH5FMHDSX7,2025-01-03,A00706,0898,A,H5FMHDSX7,None,101,Nova Seq 6000
53,267,241108_A00706_0893_AH5CVTDSX7,241017_J3TAV_Suzan,J3TAV,241108_S4FCA,2024-11-08,A00706,H5CVTDSX7,A,True,...,20241108_A00706_0893_AH5CVTDSX7.lanebarcode.html,20241108_A00706_0893_AH5CVTDSX7,2024-11-08,A00706,0893,A,H5CVTDSX7,None,101,Nova Seq 6000
54,197,240913_A00706_0877_AH5FFCDSX7,240823_77MZJ_Maria,77MZJ,240913_S4FCA,2024-09-13,A00706,H5FFCDSX7,A,True,...,240913_A00706_0877_AH5FFCDSX7_77MZJ.lanebarcod...,240913_A00706_0877_AH5FFCDSX7_77MZJ,2024-09-13,A00706,0877,A,H5FFCDSX7,[77MZJ],101,Nova Seq 6000
57,188,240801_A00706_0873_AH5CY7DSX7,240723_E5VBT_Suzan,E5VBT,240801_S4FCA,2024-08-01,A00706,H5CY7DSX7,A,True,...,240801_A00706_0873_AH5CY7DSX7_E5VBT.lanebarcod...,240801_A00706_0873_AH5CY7DSX7_E5VBT,2024-08-01,A00706,0873,A,H5CY7DSX7,[E5VBT],101,Nova Seq 6000
58,186,240730_A00706_0870_AH5FG5DSX7,240709_QQESO_Rebecca,QQESO,240730_S4FCA,2024-07-30,A00706,H5FG5DSX7,A,True,...,240730_A00706_0870_AH5FG5DSX7_QQESO.lanebarcod...,240730_A00706_0870_AH5FG5DSX7_QQESO,2024-07-30,A00706,0870,A,H5FG5DSX7,[QQESO],101,Nova Seq 6000
60,86,240621_A00706_0860_AH5F3TDSX7,240326_L5WAS_Frederik,L5WAS,240621_S4FCA,2024-06-21,A00706,H5F3TDSX7,A,True,...,240621_A00706_0860_AH5F3TDSX7_L5WAS.lanebarcod...,240621_A00706_0860_AH5F3TDSX7_L5WAS,2024-06-21,A00706,0860,A,H5F3TDSX7,[L5WAS],101,Nova Seq 6000
61,174,240507_A00706_0857_AH5FC2DSX7,240221_BWDQD_Zaruhi,BWDQD,240507_S4FCA,2024-05-07,A00706,H5FC2DSX7,A,True,...,240507_A00706_0857_AH5FC2DSX7_BWDQD.lanebarcod...,240507_A00706_0857_AH5FC2DSX7_BWDQD,2024-05-07,A00706,0857,A,H5FC2DSX7,[BWDQD],101,Nova Seq 6000
69,8,240219_A00706_0829_AH32TTDSX7,240208_2KESP_Maria,2KESP,240219_S4FCA,2024-02-19,A00706,H32TTDSX7,A,True,...,240219_A00706_0829_AH32TTDSX7_606A.lanebarcode...,240219_A00706_0829_AH32TTDSX7_606A,2024-02-19,A00706,0829,A,H32TTDSX7,None,101,Nova Seq 6000
72,5,240216_A00706_0826_AH3725DSX7,240201_L8R4I_Zaruhi,L8R4I,240216_S4FCA,2024-02-16,A00706,H3725DSX7,A,True,...,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new...,240216_A00706_0826_AH3725DSX7_L8R4I_reDMPX_new,2024-02-16,A00706,0826,A,H3725DSX7,[L8R4I],101,Nova Seq 6000
76,37,240126_A00706_0811_AHTMW2DSX5,240118_ZTM3M_Maria,ZTM3M,240126_S4FCA,2024-01-26,A00706,HTMW2DSX5,A,True,...,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,240126_A00706_0811_AHTMW2DSX5_603A,2024-01-26,A00706,0811,A,HTMW2DSX5,None,101,Nova Seq 6000

In [196]:
tusb_to_upload['sequencing_run']

0     0926
6     0912
7     0909
8     0907
9     0904
10    0900
11    0899
12    0894
13    0892
14    0882
15    0880
16    0878
17    0874
18    0872
19    0871
21    0869
23    0864
35    0828
39    0929
40    0927
41    0925
45    0914
47    0910
48    0906
49    0908
50    0903
51    0901
52    0898
53    0893
54    0877
57    0873
58    0870
60    0860
61    0857
69    0829
72    0826
76    0811
Name: sequencing_run, dtype: object

In [197]:
seq_run = tusb_to_upload['sequencing_run']
tusb_to_upload = tusb_to_upload.drop(columns=['sequencing_run'], axis=1)
tusb_to_upload['sequencing_run'] = seq_run

In [198]:
tusb_to_upload['database_insert_by'] = 'julie.bitz-thorsen@sund.ku.dk'
from datetime import datetime, timezone

ts = datetime.now(timezone.utc)  
tusb_to_upload['database_insert_datetime_utc'] = ts
from uuid import uuid4
tusb_to_upload['upload_uuid'] = uuid4()
tusb_to_upload = tusb_to_upload.replace(["nan", "NaN", "NAN", "null", "NULL", "None", "none"], None)

In [199]:
tusb_to_upload.columns

Index(['ID', 'BSSHRunID', 'WorkingID', 'seqc_tube_tag', 'RunSheetID',
       'sequencing_date', 'InstrumentID', 'flowcell_id', 'flowcell_position',
       'SequencingOK', 'Notes by Julie', 'full_flowcell_id',
       'duplicate_flowcell', 'upload_sheet', 'run', 'date', 'machine', 'side',
       'flowcell', 'ttags', 'read_length', 'sequencing_machine',
       'sequencing_run', 'database_insert_by', 'database_insert_datetime_utc',
       'upload_uuid'],
      dtype='object')

In [200]:
top_unknown_barcodes.rename(columns={
    'Flowcell ID': 'flowcell_id'}, inplace=True)

In [201]:
tusb_to_upload.drop(columns=['ID', 
                             'BSSHRunID',
                             'WorkingID',
                             'RunSheetID',
                             'InstrumentID',
                             'Notes by Julie',
                             'SequencingOK',
                             'full_flowcell_id',
                             'duplicate_flowcell',
                             'run',
                             'date',
                             'machine',
                             'side',
                             'flowcell', 
                             'ttags'],
                             inplace=True, errors='ignore')

In [202]:
tusb_to_upload = tusb_to_upload.merge(top_unknown_barcodes, how='inner', validate='one_to_many', on='flowcell_id')

In [203]:
tusb_to_upload = tusb_to_upload.rename(columns=translator_tusb)

In [204]:
tusb_to_upload

,seqc_tube_tag,sequencing_date,flowcell_id,flowcell_position,upload_sheet,read_length,sequencing_machine,sequencing_run,database_insert_by,database_insert_datetime_utc,upload_uuid,unknown_barcode_lane,unknown_barcode_count,unknown_barcode_sequence
0,5OWD7,2025-04-15,HVVTHDSXC,B,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,101,Nova Seq 6000,0926,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,1,995480,CTAAGTACGC+GCGGTATGTT
1,5OWD7,2025-04-15,HVVTHDSXC,B,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,101,Nova Seq 6000,0926,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,1,714640,CTTACCGCAC+CGAGGTCTTA
2,5OWD7,2025-04-15,HVVTHDSXC,B,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,101,Nova Seq 6000,0926,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,1,682880,GGCGCCATTG+CGTGCGCGGT
3,5OWD7,2025-04-15,HVVTHDSXC,B,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,101,Nova Seq 6000,0926,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,1,512280,TTCTTAACCA+GGGCTGTAGA
4,5OWD7,2025-04-15,HVVTHDSXC,B,20250415_A00706_0926_BHVVTHDSXC.lanebarcode.html,101,Nova Seq 6000,0926,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,1,443020,NNNNNNNNNN+NNNNNNNNNN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,ZTM3M,2024-01-26,HTMW2DSX5,A,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,101,Nova Seq 6000,0811,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,4,1813580,TACCGAGGAT+CGGTCAGGGT
1476,ZTM3M,2024-01-26,HTMW2DSX5,A,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,101,Nova Seq 6000,0811,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,4,1745580,TGATGGCTAC+CGGTTGTTGG
1477,ZTM3M,2024-01-26,HTMW2DSX5,A,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,101,Nova Seq 6000,0811,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,4,1493260,GCTGACGTTG+CCTGCGAACA
1478,ZTM3M,2024-01-26,HTMW2DSX5,A,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,101,Nova Seq 6000,0811,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,4,1383760,GAACGCAATA+CCCGTAAGAT
1479,ZTM3M,2024-01-26,HTMW2DSX5,A,240126_A00706_0811_AHTMW2DSX5_603A.lanebarcode...,101,Nova Seq 6000,0811,julie.bitz-thorsen@sund.ku.dk,2025-12-22 10:33:40.379709+00:00,64e71280-c65e-4125-b6eb-4b18c8931473,4,1374820,GTAACTTGGT+CGGTCTGGCG

In [205]:
tusb_to_upload.to_sql('top_unknown_seq_barcodes', ENGINE, if_exists='append', index=False)

480