In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"c:\Users\glj523\edna_robot_sample_202406101527.csv")

In [6]:
df.head()

,SubSampleID,RackName,RackID,PositionInRack,Mass,SampledBy,SamplingDate,RemarksSubSampling,Archive Sample ID,Submitter,SubmissionDate,RemarksSubmission,database_insert_by,from_spreadsheet,database_insert_datetime_utc,upload_uuid
0,lv7005365986,rack175,lvl900117530,e06,182.0,mh,2023-11-18 00:00:00.000,NaN,lv3005574147,kk,2023-11-17 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2...,2024-06-10 14:28:27.374 +0200,250448cc-0d8f-400e-a7ab-6f17d0fc560a
1,lv7005367348,rack52,lvl900114395,a01,192.0,mh_fm_vss,2023-10-04 00:00:00.000,NaN,lv3005888014,bds_yw,2023-03-24 00:00:00.000,NaN,upload_user,edna_subsampling_for_robot_pipeline(2023-09-27...,2024-06-10 12:13:34.387 +0200,e6d8cbe7-4f32-4f31-82dd-dfc9182984f6
2,lv7005227800,rack52,lvl900114395,b01,140.0,mh_fm_vss,2023-10-04 00:00:00.000,NaN,lv3005888008,bds_yw,2023-03-24 00:00:00.000,NaN,upload_user,edna_subsampling_for_robot_pipeline(2023-09-27...,2024-06-10 12:13:34.387 +0200,e6d8cbe7-4f32-4f31-82dd-dfc9182984f6
3,lv7005224976,rack52,lvl900114395,c01,172.0,mh_fm_vss,2023-10-04 00:00:00.000,NaN,lv3005888020,bds_yw,2023-03-24 00:00:00.000,NaN,upload_user,edna_subsampling_for_robot_pipeline(2023-09-27...,2024-06-10 12:13:34.387 +0200,e6d8cbe7-4f32-4f31-82dd-dfc9182984f6
4,lv7005224920,rack52,lvl900114395,d01,181.0,mh_fm_vss,2023-10-04 00:00:00.000,NaN,lv3005888019,bds_yw,2023-03-24 00:00:00.000,NaN,upload_user,edna_subsampling_for_robot_pipeline(2023-09-27...,2024-06-10 12:13:34.387 +0200,e6d8cbe7-4f32-4f31-82dd-dfc9182984f6

In [18]:
pd.set_option('display.max_colwidth', None)

In [20]:
df[(df["RackID"] + df["PositionInRack"]).duplicated()]

,SubSampleID,RackName,RackID,PositionInRack,Mass,SampledBy,SamplingDate,RemarksSubSampling,Archive Sample ID,Submitter,SubmissionDate,RemarksSubmission,database_insert_by,from_spreadsheet,database_insert_datetime_utc,upload_uuid
274,lv7005365787,rack173,lvl900117532,a01,161.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888102,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
275,lv7005365786,rack173,lvl900117532,b01,172.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888109,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
276,lv7005365767,rack173,lvl900117532,c01,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888103,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
277,lv7005365792,rack173,lvl900117532,d01,171.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888101,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2

In [23]:
df[df["RackID"] == "lvl900117532"].sort_values(by="PositionInRack")

,SubSampleID,RackName,RackID,PositionInRack,Mass,SampledBy,SamplingDate,RemarksSubSampling,Archive Sample ID,Submitter,SubmissionDate,RemarksSubmission,database_insert_by,from_spreadsheet,database_insert_datetime_utc,upload_uuid
270,lv7005365783,rack173,lvl900117532,a01,184.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888119,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
274,lv7005365787,rack173,lvl900117532,a01,161.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888102,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
280,lv7005365759,rack173,lvl900117532,a02,177.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888071,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
286,lv7005365778,rack173,lvl900117532,a03,155.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888050,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
292,lv7005366083,rack173,lvl900117532,a04,NaN,vss_fm,2023-10-19 00:00:00.000,negative control,NaN,ew,2023-10-19 00:00:00.000,negative control,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
298,lv7005366074,rack173,lvl900117532,a05,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888041,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
304,lv7005366064,rack173,lvl900117532,a06,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005889576,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
310,lv7005365790,rack173,lvl900117532,a07,151.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888107,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
275,lv7005365786,rack173,lvl900117532,b01,172.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888109,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
271,lv7005365794,rack173,lvl900117532,b01,179.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888114,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
281,lv7005365762,rack173,lvl900117532,b02,171.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888073,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
287,lv7005365755,rack173,lvl900117532,b03,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888045,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
293,lv7005366075,rack173,lvl900117532,b04,183.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888070,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
299,lv7005366070,rack173,lvl900117532,b05,167.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888042,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
305,lv7005366059,rack173,lvl900117532,b06,165.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005889578,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
311,lv7005366061,rack173,lvl900117532,b07,179.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888077,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
276,lv7005365767,rack173,lvl900117532,c01,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888103,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
272,lv7005365765,rack173,lvl900117532,c01,171.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888108,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
282,lv7005365769,rack173,lvl900117532,c02,179.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888076,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
288,lv7005365750,rack173,lvl900117532,c03,160.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888056,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
294,lv7005365774,rack173,lvl900117532,c04,153.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888046,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
300,lv7005366091,rack173,lvl900117532,c05,156.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888067,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
306,lv7005365771,rack173,lvl900117532,c06,163.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005889577,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
312,lv7005366090,rack173,lvl900117532,c07,168.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888024,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
277,lv7005365792,rack173,lvl900117532,d01,171.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888101,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
273,lv7005365784,rack173,lvl900117532,d01,160.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888115,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
283,lv7005365777,rack173,lvl900117532,d02,156.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888072,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
289,lv7005365795,rack173,lvl900117532,d03,170.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888051,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
295,lv7005365766,rack173,lvl900117532,d04,159.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888066,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
301,lv7005366063,rack173,lvl900117532,d05,176.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888043,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
307,lv7005366057,rack173,lvl900117532,d06,166.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005889579,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
313,lv7005366081,rack173,lvl900117532,d07,180.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888044,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
278,lv7005365754,rack173,lvl900117532,e01,160.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888112,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
284,lv7005365753,rack173,lvl900117532,e02,182.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888078,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
290,lv7005365751,rack173,lvl900117532,e03,182.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888053,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
296,lv7005366095,rack173,lvl900117532,e04,152.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888062,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
302,lv7005366096,rack173,lvl900117532,e05,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888061,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
308,lv7005366072,rack173,lvl900117532,e06,162.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888054,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
314,lv7005366066,rack173,lvl900117532,e07,160.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888059,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
279,lv7005365760,rack173,lvl900117532,f01,178.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888093,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
285,lv7005366321,rack173,lvl900117532,f02,167.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888084,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
291,lv7005010760,rack173,lvl900117532,f03,163.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888055,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
297,lv7005366060,rack173,lvl900117532,f04,168.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888065,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
303,lv7005366084,rack173,lvl900117532,f05,152.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005889580,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
309,lv7005366067,rack173,lvl900117532,f06,156.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005888057,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2
315,lv7005366071,rack173,lvl900117532,f07,156.0,vss_fm,2023-10-19 00:00:00.000,NaN,lv3005887693,ew,2023-10-19 00:00:00.000,NaN,upload_user,ordering_edna_subsampling_for_robot_pipeline(2023-10-19_ew_antarcticaps104).txt,2024-06-10 14:16:22.960 +0200,781bc17d-c482-4488-b658-53dd46328fb2